# 1.문제정의
- 유방암 화나 데이터를 사용해서 유방암의 정도를 예측해보자

# 2.데이터 수집

In [1]:
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer()

In [11]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
#malignant : 암
#benign : 암이 아니다
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [7]:
cancer['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

# 3. 데이터 전처리

In [8]:
import pandas as pd
import numpy as np

In [9]:
#문제데이터
X=pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [13]:
#정답데이터
y=pd.DataFrame(cancer['target'],columns=['cancer'])
y.head()

cancer
0       0
1       0
2       0
3       0
4       0

# 4. 탐색적 데이터 분석
- 생략

# 데이터 스케일링
- 데이터 전처리를 마무리하고 실행
- 원래 가지고 있던 데이터의 의미가 변형되기 때문에 모든 전처리를 마무리 한 후에 사용

In [20]:
from sklearn.preprocessing import RobustScaler, MinMaxScaler, StandardScaler

In [22]:
# 1.스케일링 모델 불러오기
rbs=RobustScaler()
# 2.가지고 있는 데이터로 스케일링 모델에 학습 > 어떤 값이 어떻게 변하는지 파악
rbs.fit(X)
# 3.파악된 규칙을 통해서 값을 변형
X_rbs=rbs.transform(X)

In [23]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [24]:
X_rbs

array([[ 1.13235294, -1.5026643 ,  1.26374006, ...,  1.71524826,
         2.63555556,  1.88457808],
       [ 1.76470588, -0.19005329,  1.61285862, ...,  0.89219446,
        -0.10666667,  0.43549952],
       [ 1.54901961,  0.42806394,  1.51261666, ...,  1.48305173,
         1.17185185,  0.3656644 ],
       ...,
       [ 0.79166667,  1.64120782,  0.76253025, ...,  0.43402094,
        -0.89481481, -0.08923375],
       [ 1.77205882,  1.86323268,  1.86173522, ...,  1.7111019 ,
         1.87407407,  2.13191077],
       [-1.375     ,  1.01243339, -1.32457656, ..., -1.03586607,
         0.07259259, -0.46799224]])

In [31]:
mms=MinMaxScaler()
mms.fit(X)
X_mms=mms.transform(X)

In [32]:
X_mms

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [40]:
sds=StandardScaler()
sds.fit(X)
X_sds=sds.transform(X)

In [41]:
X_sds

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

# 5. 모델 선택 및 하이퍼 파라미터 튜닝

In [48]:
#train 과 test로 데이터 분리
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [34]:
#KNN 모델 불러오기
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

# 6. 학습

In [49]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

# 7.평가 및 예측

In [29]:
#경고창 지우기
import warnings
warnings.filterwarnings(action='ignore')

In [50]:
from sklearn.model_selection import cross_val_score
cross_val_score(knn,X_train,y_train,cv=5).mean()

0.9248700410396717

In [51]:
X_train,X_test,y_train,y_test=train_test_split(X_rbs,y)
knn.fit(X_train,y_train)
cross_val_score(knn,X_train,y_train,cv=5).mean()

0.9695212038303694

In [52]:
X_train,X_test,y_train,y_test=train_test_split(X_mms,y)
knn.fit(X_train,y_train)
cross_val_score(knn,X_train,y_train,cv=5).mean()

0.9624623803009577

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X_sds,y)
knn.fit(X_train,y_train)
cross_val_score(knn,X_train,y_train,cv=5).mean()

0.9647879616963065

In [ ]:
#분류는 정확도라는 지표를 사용
# 몇개 중에 몇개 맞췄는가 100개 중에 92개 맞춤 = 0.92
#암 VS 암 아닌지
#모델 알고리즘(규칙) : 모든 사람은 암이다
#암 환자 데이터 95개, 암 환자가 아닌 데이터 5개 = 0.95

In [54]:
#다양한 평가지표 확인하기
y_pred=knn.predict(X_test)

In [56]:
#precision : 정밀도, 애매한거 사용 안함
#recall : 재현율, 애매한거 사용
#f1-score : 정밀도와 재현율의 조화평균
## 셋 다 0~ 1까지의 값을 갖는다. 1에 가까울수록 좋음
#support : 데이터의 수
#accuracy : 전체 중에 맞춘 비율
#macro avg : 단순 평균,(1.00+0.98)/2
#weighted avg : 가중 평균, 값이 많은 데이터가 높은 가중치를 갖는다
#               0.96 *0.2 + 1.00 * 0.8 = 0.99
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        55
           1       0.98      1.00      0.99        88

    accuracy                           0.99       143
   macro avg       0.99      0.98      0.99       143
weighted avg       0.99      0.99      0.99       143

